<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_shop"
 *
 * Auto generated by Extension Builder 2016-05-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW Shop',
	'description' => '',
	'category' => 'plugin',
    'author' => 'Steffen Kroggel',
    'author_email' => 'developer@steffenkroggel.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'clearCacheOnLoad' => 0,
	'version' => '10.4.5',
	'constraints' => [
		'depends' => [
            'typo3' => '10.4.0-10.4.99',
            'accelerator' => '10.5.17-12.4.99',
            'core_extended' => '10.4.0-12.4.99',
            'ajax_api' => '10.4.0-12.4.99',
            'postmaster' => '10.4.0-12.4.99',
            'fe_register' => '10.4.0-12.4.99',
            'rkw_basics' => '10.4.0-12.4.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];
